version: 0.2

phases:
  pre_build:
    commands:
      - npm instal 
  build:
    commands:
      - npm run build --production

artifacts:
  files:
    - '**/*'
    discard-path: no
    base-directory: build